print('*'*50)
print('          DOBRO, TRIPLO E RAÍZ QUADRADA')
print('*'*50)
val=int(input('               DIGITE UM VALOR: '))
print('*'*50)
print ('')
print ('')
print('*'*50)
print('O DOBRO DE {} É {}'.format(val, val*2))
print('O TRIPLO DE {} É {}'.format(val, val*3))
print('{}^2 É {}'.format(val, val**2))
print('A RAÍZ QUADRADA DE {} É {:.2f}'.format(val, val**(1/2)))
print ('#'*50)