print('')
valor = input('Digite qualquer coisa: ')
print('')
print('O que você digitou é do tipo: ', type(valor))
print('É alfanumérico? ', valor.isalnum())
print('É alfabético? ', valor.isalpha())
print('É um digito? ', valor.isdigit())
print('Esta em caixa baixa? ', valor.islower())
print(' Esta em caixa alta? ', valor.isupper())
print(' O primeiro valor está em caixa alta? ', valor.istitle())
print(' É um valor decimal? ', valor.isdecimal())
print(' É um número? ', valor.isnumeric())
print(' Só tem espaços? ', valor.isspace())

