print('*'*50)
print('*'*10, 'ESCOLA TARTARUGA SALTITANTE', '*'*11)
print('')
print('*'*21, 'NOTAS', '*'*22)
print('*'*50)
n1=float(input('PRIMEIRO BIMESTRE: '))
n2=float(input('SEGUNDO BIMESTRE: '))
n3=float(input('TERCEIRO BIMESTRE: '))
n4=float(input('QUARTO BIMESTRE: '))
print('*'*50)
med=(n1+n2+n3+n4)/4
print('A MÉDIA DESTE ALUNO É: {:.2f}'.format(med))
print('*'*50)