winners = ('Chad Michaels', 'Alaska', 'Trixie Mattel', 'Monet X-Change', 'Trinity, the Tuck', 'Shea Coulea', 'Kyle Sonique Love')
print()
print('Lista com todas as campeãs de Drag Race - All Stars: \n', winners)
print()
print('As 5 primeiras campeãs são: \n', winners[0:5])
print()
print('As 4 últimas são: \n', winners[-4:])
print()
print('As campeãs em ordem alfabética: \n', sorted(winners) )
print()
print('Alaska está na {}ª posição'.format(winners.index('Alaska')))
